// schemas/property.js

export default {
  name: 'property',
  title: 'Property',
  type: 'document',
  fields: [
    {
        name: 'contact',
        title: 'Contact',
        type: 'reference',
        to: [{ type: 'agent' }], // Changed from 'user' to 'agent'
        options: { required: true },
      },
    {
      name: 'name',
      title: 'Name',
      type: 'string',
      options: { default: 'Proxy Admin' },
    },
    {
      name: 'email',
      title: 'Email',
      type: 'string',
      options: { default: 'proxy@nextlevel.com' },
    },
    {
        name: 'id',
        title: 'User ID',
        type: 'string', // Changed to string for a generic ID
        options: { default: null },
      },
      {
        name: 'type',
        title: 'Property Type',
        type: 'string',
        options: {
          list: [
            { title: 'Retail', value: 'Retail' },
            { title: 'Office', value: 'Office' },
            { title: 'Investment Sale', value: 'Investment Sale' },
            { title: 'Rental', value: 'Rental' },
            { title: 'Residential', value: 'Residential' },
            { title: 'Commercial', value: 'Commercial' },
          ],
          default: 'Property type not provided',
        },
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      options: { default: 'No description provided' },
    },
    {
      name: 'location',
      title: 'Location',
      type: 'object',
      fields: [
        { name: 'street', title: 'Street', type: 'string' },
        { name: 'city', title: 'City', type: 'string' },
        { name: 'state', title: 'State', type: 'string' },
        { name: 'zipcode', title: 'Zipcode', type: 'string' },
      ],
    },
    {
      name: 'amenities',
      title: 'Amenities',
      type: 'array',
      of: [{ type: 'string' }],
      options: { default: [] },
    },
    {
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'Residential', value: 'Residential' },
          { title: 'Commercial', value: 'Commercial' },
        ],
        required: true,
      },
    },
    {
      name: 'retail',
      title: 'Retail Attributes',
      type: 'object',
      fields: [
        { name: 'address', title: 'Address', type: 'string' },
        { name: 'crossStreets', title: 'Cross Streets', type: 'string' },
        { name: 'neighborhood', title: 'Neighborhood', type: 'string' },
        { name: 'pricePerMonth', title: 'Price Per Month', type: 'number' },
        { name: 'priceAnnual', title: 'Price Annual', type: 'number' },
        { name: 'size', title: 'Size', type: 'number' },
        { name: 'psf', title: 'Price Per Square Foot', type: 'number' },
        { name: 'basement', title: 'Basement', type: 'boolean', options: { default: false } },
        { name: 'frontage', title: 'Frontage', type: 'number' },
        { name: 'ceilingHeight', title: 'Ceiling Height', type: 'number' },
        { name: 'cookingAllowed', title: 'Cooking Allowed', type: 'boolean', options: { default: false } },
        { name: 'popUpAllowed', title: 'Pop-Up Allowed', type: 'boolean', options: { default: false } },
        { name: 'neighbors', title: 'Neighbors', type: 'array', of: [{ type: 'string' }] },
      ],
    },
    {
      name: 'office',
      title: 'Office Attributes',
      type: 'object',
      fields: [
        { name: 'address', title: 'Address', type: 'string' },
        { name: 'suite', title: 'Suite', type: 'string' },
        { name: 'crossStreets', title: 'Cross Streets', type: 'string' },
        { name: 'neighborhood', title: 'Neighborhood', type: 'string' },
        { name: 'priceMonthly', title: 'Price Monthly', type: 'number' },
        { name: 'priceYearly', title: 'Price Yearly', type: 'number' },
        { name: 'size', title: 'Size', type: 'number' },
        { name: 'psf', title: 'Price Per Square Foot', type: 'number' },
        { name: 'numberOfOffices', title: 'Number of Offices', type: 'number' },
        { name: 'numberOfConferenceRooms', title: 'Number of Conference Rooms', type: 'number' },
        { name: 'ceilingHeight', title: 'Ceiling Height', type: 'number' },
        { name: 'kitchen', title: 'Kitchen', type: 'boolean', options: { default: false } },
        { name: 'bathrooms', title: 'Bathrooms', type: 'number' },
      ],
    },
    {
      name: 'investmentSale',
      title: 'Investment Sale Attributes',
      type: 'object',
      fields: [
        { name: 'assetType', title: 'Asset Type', type: 'string', options: {
          list: [
            { title: 'Entire Building', value: 'Entire Building' },
            { title: 'Condo', value: 'Condo' },
            { title: 'Coop Land', value: 'Coop Land' },
            { title: 'Hotel', value: 'Hotel' },
            { title: 'Industrial', value: 'Industrial' },
          ],
        }},
        { name: 'portfolio', title: 'Portfolio', type: 'boolean', options: { default: false } },
        { name: 'sizeAvailable', title: 'Size Available', type: 'number' },
        { name: 'price', title: 'Price', type: 'number' },
        { name: 'psf', title: 'Price Per Square Foot', type: 'number' },
        { name: 'totalBuildingSize', title: 'Total Building Size', type: 'number' },
        { name: 'lotSize', title: 'Lot Size', type: 'number' },
        { name: 'buildingDimensions', title: 'Building Dimensions', type: 'string' },
        { name: 'occupied', title: 'Occupied', type: 'boolean', options: { default: false } },
        { name: 'floors', title: 'Floors', type: 'number' },
        { name: 'numberOfUnits', title: 'Number of Units', type: 'number' },
        { name: 'averageFloorSize', title: 'Average Floor Size', type: 'number' },
        { name: 'grossIncome', title: 'Gross Income', type: 'number' },
        { name: 'realEstateTax', title: 'Real Estate Tax', type: 'number' },
        { name: 'totalExpenses', title: 'Total Expenses', type: 'number' },
        { name: 'noi', title: 'Net Operating Income', type: 'number' },
        { name: 'far', title: 'Floor Area Ratio', type: 'number' },
        { name: 'airRights', title: 'Air Rights', type: 'boolean', options: { default: false } },
        { name: 'capRate', title: 'Capitalization Rate', type: 'number' },
        { name: 'zoning', title: 'Zoning', type: 'string' },
        { name: 'capEx', title: 'Capital Expenditures', type: 'number' },
        { name: 'loadingDock', title: 'Loading Dock', type: 'boolean', options: { default: false } },
      ],
    },
    {
      name: 'images',
      title: 'Images',
      type: 'array',
      of: [{ type: 'image' }],
      options: { default: [] },
    },
    {
      name: 'isFeatured',
      title: 'Is Featured',
      type: 'boolean',
      options: { default: false },
    },
    {
      name: 'forSale',
      title: 'For Sale',
      type: 'boolean',
      options: { default: true },
    },
    {
      name: 'forRent',
      title: 'For Rent',
      type: 'boolean',
      options: { default: false },
    },
    {
      name: 'acceptsCrypto',
      title: 'Accepts Crypto',
      type: 'boolean',
      options: { default: false },
    },
    {
      name: 'numberOfBookmarks',
      title: 'Number of Bookmarks',
      type: 'number',
      options: { default: 0 },
    },
    {
      name: 'inClosing',
      title: 'In Closing',
      type: 'boolean',
      options: { default: false },
    },
    {
      name: 'interestedBy',
      title: 'Interested By',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'client' }] }],
      options: { default: [] },
    },
    {
      name: 'offers',
      title: 'Offers',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'offer' }] }],
      options: { default: [] },
    },
    {
      name: 'comments',
      title: 'Comments',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'comment' }] }],
      options: { default: [] },
    },
  
    {
      name: 'onMarket',
      title: 'On Market',
      type: 'boolean',
      options: { default: true },
    },
    {
      name: 'views',
      title: 'Views',
      type: 'number',
      options: { default: 0 },
    },
    {
      name: 'daysOnMarket',
      title: 'Days on Market',
      type: 'number',
      options: { default: 0 },
    },
    {
      name: 'showPropertyDayOnMarket',
      title: 'Show Property Day on Market',
      type: 'boolean',
      options: { default: true },
    },
    {
        name: 'assignedTo',
        title: 'Assigned To',
        type: 'array',
        of: [{ type: 'reference', to: [{ type: 'agent' }] }], // Changed to reference 'agent'
        options: { default: [] },
      },
      {
        name: 'payments',
        title: 'Payments',
        type: 'array',
        of: [{ type: 'reference', to: [{ type: 'payment' }] }],
        options: { default: [] },
   },
  ],
  preview: {
    select: {
      title: 'name',
      media: 'images[0]',
    },
  },
};
